// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiType int32

const (
	ApiType_Common   ApiType = 0
	ApiType_Client   ApiType = 1
	ApiType_Server   ApiType = 2
	ApiType_Internal ApiType = 3
)

var ApiType_name = map[int32]string{
	0: "Common",
	1: "Client",
	2: "Server",
	3: "Internal",
}

var ApiType_value = map[string]int32{
	"Common":   0,
	"Client":   1,
	"Server":   2,
	"Internal": 3,
}

func (x ApiType) String() string {
	return proto.EnumName(ApiType_name, int32(x))
}

func (ApiType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

type ConnCodeGenWay int32

const (
	ConnCodeGenWay_NoGen ConnCodeGenWay = 0
	ConnCodeGenWay_Mock  ConnCodeGenWay = 1
	ConnCodeGenWay_Rpc   ConnCodeGenWay = 2
	ConnCodeGenWay_All   ConnCodeGenWay = 3
)

var ConnCodeGenWay_name = map[int32]string{
	0: "NoGen",
	1: "Mock",
	2: "Rpc",
	3: "All",
}

var ConnCodeGenWay_value = map[string]int32{
	"NoGen": 0,
	"Mock":  1,
	"Rpc":   2,
	"All":   3,
}

func (x ConnCodeGenWay) String() string {
	return proto.EnumName(ConnCodeGenWay_name, int32(x))
}

func (ConnCodeGenWay) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

type GetOrCreateAccountRequest struct {
	// 用户账号 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户账号密码
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrCreateAccountRequest) Reset()         { *m = GetOrCreateAccountRequest{} }
func (m *GetOrCreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrCreateAccountRequest) ProtoMessage()    {}
func (*GetOrCreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *GetOrCreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrCreateAccountRequest.Unmarshal(m, b)
}
func (m *GetOrCreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrCreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetOrCreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrCreateAccountRequest.Merge(m, src)
}
func (m *GetOrCreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrCreateAccountRequest.Size(m)
}
func (m *GetOrCreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrCreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrCreateAccountRequest proto.InternalMessageInfo

func (m *GetOrCreateAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetOrCreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccountInfo struct {
	// 昵称   此处用作示例，实际场景按需求添加字段
	Nickname             string         `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Key                  []string       `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Way                  ConnCodeGenWay `protobuf:"varint,3,opt,name=way,proto3,enum=account.ConnCodeGenWay" json:"way,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AccountInfo) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AccountInfo) GetWay() ConnCodeGenWay {
	if m != nil {
		return m.Way
	}
	return ConnCodeGenWay_NoGen
}

type GetOrCreateAccountResponse struct {
	// 错误码
	ErrorCode uint32 `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 是否是新创建的账号
	IsCreated bool `protobuf:"varint,2,opt,name=isCreated,proto3" json:"isCreated,omitempty"`
	// 账号具体信息
	Account              *AccountInfo `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetOrCreateAccountResponse) Reset()         { *m = GetOrCreateAccountResponse{} }
func (m *GetOrCreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrCreateAccountResponse) ProtoMessage()    {}
func (*GetOrCreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *GetOrCreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrCreateAccountResponse.Unmarshal(m, b)
}
func (m *GetOrCreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrCreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetOrCreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrCreateAccountResponse.Merge(m, src)
}
func (m *GetOrCreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrCreateAccountResponse.Size(m)
}
func (m *GetOrCreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrCreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrCreateAccountResponse proto.InternalMessageInfo

func (m *GetOrCreateAccountResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetOrCreateAccountResponse) GetIsCreated() bool {
	if m != nil {
		return m.IsCreated
	}
	return false
}

func (m *GetOrCreateAccountResponse) GetAccount() *AccountInfo {
	if m != nil {
		return m.Account
	}
	return nil
}

var E_Type = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*ApiType)(nil),
	Field:         50001,
	Name:          "account.Type",
	Tag:           "varint,50001,opt,name=Type,enum=account.ApiType",
	Filename:      "account.proto",
}

var E_GenWay = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*ConnCodeGenWay)(nil),
	Field:         50002,
	Name:          "account.GenWay",
	Tag:           "varint,50002,opt,name=GenWay,enum=account.ConnCodeGenWay",
	Filename:      "account.proto",
}

func init() {
	proto.RegisterEnum("account.ApiType", ApiType_name, ApiType_value)
	proto.RegisterEnum("account.ConnCodeGenWay", ConnCodeGenWay_name, ConnCodeGenWay_value)
	proto.RegisterType((*GetOrCreateAccountRequest)(nil), "account.GetOrCreateAccountRequest")
	proto.RegisterType((*AccountInfo)(nil), "account.AccountInfo")
	proto.RegisterType((*GetOrCreateAccountResponse)(nil), "account.GetOrCreateAccountResponse")
	proto.RegisterExtension(E_Type)
	proto.RegisterExtension(E_GenWay)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0xda, 0x25, 0xb1, 0x27, 0x34, 0x5a, 0xad, 0x90, 0x30, 0x11, 0x42, 0x91, 0xb9, 0x84,
	0x1e, 0x1c, 0x29, 0x1c, 0x90, 0xca, 0x29, 0xe4, 0x10, 0xe5, 0x50, 0x2a, 0x2d, 0x95, 0x90, 0xb8,
	0xb9, 0xf6, 0x24, 0x58, 0x71, 0x76, 0xcc, 0x7a, 0x43, 0x95, 0x3f, 0x50, 0xe5, 0xc8, 0x9f, 0xe9,
	0x0f, 0x81, 0x5f, 0x84, 0xec, 0x75, 0x12, 0x10, 0x1f, 0xb9, 0xcd, 0x8c, 0xdf, 0x3c, 0xbf, 0xf7,
	0x76, 0xe0, 0x3c, 0x4e, 0x12, 0xda, 0x28, 0x13, 0x15, 0x9a, 0x0c, 0x89, 0x4e, 0xd3, 0xf6, 0x07,
	0x4b, 0xa2, 0x65, 0x8e, 0xa3, 0x7a, 0x7c, 0xbb, 0x59, 0x8c, 0x52, 0x2c, 0x13, 0x9d, 0x15, 0x86,
	0xb4, 0x85, 0x86, 0x33, 0x78, 0x36, 0x43, 0x73, 0xad, 0xa7, 0x1a, 0x63, 0x83, 0x13, 0xbb, 0x27,
	0xf1, 0xcb, 0x06, 0x4b, 0x23, 0x7a, 0xe0, 0x64, 0x69, 0xc0, 0x06, 0x6c, 0xe8, 0x4b, 0x27, 0x4b,
	0x45, 0x1f, 0xbc, 0x22, 0x2e, 0xcb, 0x3b, 0xd2, 0x69, 0xe0, 0xd4, 0xd3, 0x43, 0x1f, 0x2e, 0xa0,
	0xdb, 0x6c, 0xcf, 0xd5, 0x82, 0x2a, 0xa8, 0xca, 0x92, 0x95, 0x8a, 0xd7, 0xd8, 0x10, 0x1c, 0x7a,
	0xc1, 0xc1, 0x5d, 0xe1, 0x36, 0x70, 0x06, 0xee, 0xd0, 0x97, 0x55, 0x29, 0x5e, 0x81, 0x7b, 0x17,
	0x6f, 0x03, 0x77, 0xc0, 0x86, 0xbd, 0xf1, 0xd3, 0x68, 0xef, 0x66, 0x4a, 0x4a, 0x4d, 0x29, 0xc5,
	0x19, 0xaa, 0x8f, 0xf1, 0x56, 0x56, 0x98, 0x70, 0xc7, 0xa0, 0xff, 0x37, 0xc5, 0x65, 0x41, 0xaa,
	0x44, 0xf1, 0x1c, 0x7c, 0xd4, 0x9a, 0x74, 0xb5, 0x56, 0xff, 0xf8, 0x5c, 0x1e, 0x07, 0xd5, 0xd7,
	0xac, 0xb4, 0x8b, 0xd6, 0x81, 0x27, 0x8f, 0x03, 0x11, 0xc1, 0x3e, 0xb8, 0x5a, 0x49, 0x77, 0xfc,
	0xe4, 0xa0, 0xe4, 0x17, 0x6b, 0x72, 0x0f, 0xba, 0x78, 0x0b, 0x9d, 0x49, 0x91, 0xdd, 0x6c, 0x0b,
	0x14, 0x00, 0xed, 0x29, 0xad, 0xd7, 0xa4, 0x78, 0xab, 0xae, 0xf3, 0x0c, 0x95, 0xe1, 0xac, 0xaa,
	0x3f, 0xa0, 0xfe, 0x8a, 0x9a, 0x3b, 0xe2, 0x31, 0x78, 0x73, 0x65, 0x50, 0xab, 0x38, 0xe7, 0xee,
	0xc5, 0x1b, 0xe8, 0xfd, 0x6e, 0x4f, 0xf8, 0xf0, 0xe8, 0x3d, 0xcd, 0xb0, 0xa2, 0xf0, 0xe0, 0xec,
	0x8a, 0x92, 0x15, 0x67, 0xa2, 0x03, 0xae, 0x2c, 0x12, 0xee, 0x54, 0xc5, 0x24, 0xcf, 0xb9, 0x3b,
	0xd6, 0xd0, 0x69, 0xd4, 0x88, 0x25, 0x88, 0xe5, 0x1f, 0x51, 0x88, 0xf0, 0xa0, 0xfa, 0x9f, 0x2f,
	0xdb, 0x7f, 0xf9, 0x5f, 0x8c, 0xcd, 0x32, 0xf4, 0x76, 0x0f, 0x41, 0xeb, 0xdb, 0x43, 0xd0, 0xba,
	0x9c, 0xc3, 0x59, 0x6d, 0xf3, 0x45, 0x64, 0x0f, 0x2a, 0xda, 0x1f, 0x54, 0x74, 0x85, 0xe6, 0x33,
	0xa5, 0xd7, 0x85, 0xc9, 0x48, 0x95, 0xc1, 0xf7, 0x7b, 0xfb, 0x84, 0xfc, 0x18, 0x9c, 0x0d, 0x48,
	0xd6, 0xfb, 0x3b, 0xc6, 0x2e, 0x6f, 0xa0, 0xdd, 0xf8, 0x3d, 0x45, 0xf6, 0xe3, 0xfe, 0xc4, 0x3d,
	0x34, 0x44, 0x3b, 0xc6, 0xde, 0x75, 0x3f, 0xf9, 0xd1, 0xa8, 0x81, 0xdd, 0xb6, 0x6b, 0xc2, 0xd7,
	0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x12, 0xfe, 0x1c, 0x36, 0x16, 0x03, 0x00, 0x00,
}
