// Code generated by CodeGenerator. DO NOT EDIT!
//
// Source: account.proto
// Time: 2022-12-02 15:00:42

package grpc

import (
	"ProjectX/service/account/pb/account"
	"ProjectX/service/account/rpc/define"

	"context"
	"google.golang.org/grpc"
)

type grpcAccount struct {
	client *grpc.ClientConn
}

func NewGrpcAccount(address string) define.Account {
	client, err := grpc.Dial(address)
	if err != nil {
		return nil
	}
	return &grpcAccount{
		client: client,
	}
}

func (r *grpcAccount) GetOrCreateAccount(ctx context.Context, in *define.GetOrCreateAccountRequest) (*define.GetOrCreateAccountResponse, error) {
	client := account.NewAccountClient(r.client)
	return client.GetOrCreateAccount(ctx, in)
}
